### ISSUE TITLE
torch and cuda version?

### ISSUE THREAD

**Issue by juanmed** [locuslab/mpc.pytorch#18]
Hello,

Thanks for sharing your this project. I had some issues running the examples and seem to be related to torch version. I am currently using torch 1.2.0 and CUDA10.0, could you please tell me the latest torch and cuda version used with this project?

I am getting errors like this:
```bash
(.mpc) user@userlabpc:~/git_clone/mpc.pytorch/examples$ python pendulum.py 
Tmp dir: /tmp/tmp7hokco9j
  0%|                                                                                      | 0/100 [00:00<?, ?it/s]/pytorch/torch/csrc/autograd/python_function.cpp:638: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
  0%|                                                                                      | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "pendulum.py", line 80, in <module>
    )(x, QuadCost(Q, p), dx)
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/mpc.py", line 265, in forward
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/mpc.py", line 362, in solve_lqr_subproblem
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/lqr_step.py", line 112, in forward
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/lqr_step.py", line 303, in lqr_backward
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/pnqp.py", line 31, in pnqp
  File "/home/user/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.
```

```bash
Traceback (most recent call last):
  File "/home/fer/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fer/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/mpc.py", line 265, in forward
  File "/home/fer/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/mpc.py", line 362, in solve_lqr_subproblem
  File "/home/fer/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/lqr_step.py", line 114, in forward
  File "/home/fer/git_clone/mpc.pytorch/.mpc/lib/python3.5/site-packages/mpc-0.0.3-py3.5.egg/mpc/lqr_step.py", line 344, in lqr_forward
AttributeError: module 'torch' has no attribute 'any'
```

Thank you very much.

**Comment by juanmed** [comment]
To add to the comment, I have tried pytorch versions 1.2.0, 0.3.1, 0.4.0, 1.0.0 and 1.2.0 and on none of them I am able to run any example. Looking at the .travis file it seems the installation is done using:

```bash
conda install pytorch
```
which looking around the internet apparently installs some version of pytorch which is none of the official Pytorch releases. Actually trying to install pytorch using `pip` always results in errors.

**Comment by juanmed** [comment]
It is `pytorch== 1.1.0`. For `pytorch==1.2.0` there are [braking changes](https://github.com/pytorch/pytorch/releases/tag/v1.2.0).

**Comment by bamos** [comment]
Thanks for letting me know! I try to keep things working with the latest PyTorch version and just pushed in some changes that lets the code still run there -- although with PyTorch changing the `Function` interface there are a lot of deprecation warnings that need to be fixed by updating `LqrStep` to the latest interface

**Comment by juanmed** [comment]
Thanks for your answer. By the way, could you please point to any examples loading data and making all computations on GPU? I am hoping to maximize the performance of your MPC using GPU. Thanks!

**Comment by bamos** [comment]
It should work if you pass in all cuda tensors: https://github.com/locuslab/mpc.pytorch/blob/master/tests/test_mpc.py#L274

But the sequential/iterative nature of the code doesn't make it very GPU-amenable so you might not see much gains from running on the GPU

**Comment by bamos** [comment]
(The code internally handles GPU inputs with `type_as` -- which should be updated to something that more explicitly handles devices with `to` but is working for now)

**Comment by juanmed** [comment]
I see, there is something I have not yet understand about your Optnet and Differentiable MPC papers then. I thought about doing real-time control using MPC for a  linear system on the GPU based on your work. 

> It should work if you pass in all cuda tensors: https://github.com/locuslab/mpc.pytorch/blob/master/tests/test_mpc.py#L274
> 
> But the sequential/iterative nature of the code doesn't make it very GPU-amenable so you might not see much gains from running on the GPU

Could you please be more specific on the issue here? Are you talking about the problem of cpu-gpu loading/offloading in a loop? Thanks.

**Comment by bamos** [comment]
The GPU's usually useful for OptNet/MPC acceleration here if you're solving many problems at the same time since the operations are batched, but otherwise if you're just solving a single problem it's probably not going to be faster than the CPU version -- no cpu-gpu transfers happen that slows it down, just the sequential nature.

Also the torch JIT wasn't really around/used much when I was developing this library but it should give very significant performance gains here on the CPU and GPU
