### ISSUE TITLE
Error in pendulum control

### ISSUE THREAD

**Issue by camontblanc** [locuslab/mpc.pytorch#22]
Hi @bamos !
I'm trying to run the pendulum's example but in the MPC constructor, I think there is an error. The output is the following:

`
Traceback (most recent call last):

  File "<ipython-input-11-cfbbc6e34fa1>", line 54, in <module>
    )(x, QuadCost(Q, p), pend)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/mpc/mpc.py", line 265, in forward
    x_init, C, c, F, f, cost, dx, x, u)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/mpc/mpc.py", line 362, in solve_lqr_subproblem
    x, u = _lqr(x_init, C, c, F, f if f is not None else e)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/mpc/lqr_step.py", line 112, in forward
    Ks, ks, self.back_out = self.lqr_backward(C, c_back, F, f_back)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/mpc/lqr_step.py", line 303, in lqr_backward
    x_init=prev_kt, n_iter=20)

  File "/home/carlos/anaconda3/lib/python3.7/site-packages/mpc/pnqp.py", line 45, in pnqp
    g_[Ic.bool()] = 0.

AttributeError: 'Tensor' object has no attribute 'bool'
`

I really appreciate if you could help me out!

**Comment by bamos** [comment]
I think your torch version is old and I try to keep this updated with the latest pytorch version -- can you try updating to the latest pytorch version and try again?

**Comment by camontblanc** [comment]
Hi @bamos !
I just updated torch to 1.2.0 and everything seems to work just fine!
Thank you very much!

**Comment by bamos** [comment]
great :)
